import Head from "next/head";

export default function Layout({ children }) {
  return (
    <div>
      <Head>
        <title>Natours | Exciting tours for adventurous people</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.png" />
      </Head>
      {children}
    </div>
  );
}
